global using AutoMapper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Music_API.Data.DAL;
global using Music_API.Data.Model;
global using Music_API.DTOs;
global using Music_API.Entities;
global using System.Reflection;